name: Node.js CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  schedule:
    - cron: '0 */6 * * *'  # BY [non ou oswa nickname ou vle mete]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18.x'
      - name: Install dependencies
        run: npm install
      - name: Run bot
        run: node index.jsprojet-bot/
├── index.js
├── package.json
└── .github/
    └── workflows/
        └── deploy.yml
